### ISSUE TITLE
Use waybar-hyprland from official flake

### ISSUE THREAD

**Issue by woojiq** [MatthiasBenaets/nix-dotfiles#10]
FYI, the official Hyprland flake now has overlay for waybar, so we don't need to write overlays ourselves. Both solutions work, but I thought you might be interested. As a newbie coming from your YouTube video, it would be easier for me to use the existing overlay. [Mini-guide](https://github.com/hyprwm/Hyprland/discussions/1729#discussioncomment-5272045).

P.S. Thanks for the youtube video, the only complete (almost :smiley: ) video tutorial I found about _nixos + home-manager + flakes_ together.

Cheers.

**Comment by MatthiasBenaets** [comment]
Interesting, thanks for the heads up.
It seems this was is correctly added late January.
I might update the config for this (not that it is much of a difference).

**Comment by MatthiasBenaets** [comment]
Closing this with d1b9323.
The custom overlay shouldn't be in the waybar modules since it can be used with other DE modules, which can cause issues. 
The hyprland waybar overlay is now used at `modules/desktop/hyprland/default.nix`.
