### ISSUE TITLE
autostart hyprland with autologin

### ISSUE THREAD

**Issue by spector700** [MatthiasBenaets/nix-dotfiles#11]
Hey, I watched your great youtube video and I have been using your configs to build mine out. I have got hyprland working without a display manager. It starts when I login to tty1 with this:

```
  environment = {
    loginShellInit = ''
      if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
        ${exec}
      fi
    '';     
```

Is there a way to autostart hyprland without having to login?

**Comment by MatthiasBenaets** [comment]
Hi and thanks,

I guess you can use any display manager that has an auto-login feature.
But if you want to keep it minimal, maybe greetd is a good solution. Like so:

```nix
services.greetd = { 
  enable = true;
  settings = {
    default_session = {
      command = "Hyprland";
      user = "youruserhere";
    };
  };
};
```

I wouldn't recommend it for obvious safety reasons, but hope it helps.

**Comment by spector700** [comment]
Thank you that worked.

also, I am using lazyvim for my neovim config, I added the plugin for neovim but it doesn't seem to do anything.

```
        packages.myVimPackages = with pkgs.vimPlugins; {
          start = [
            LazyVim
           ];
```

do you know how I would be able to handle having layvim or nvchad in my config?
